apiVersion: v2
name: game-server-library
description: A library chart for common game server resources
type: library
version: 2026.01.1
appVersion: "2026.01.1"

keywords:
  - games
  - game-server
  - library

home: https://github.com/CraightonH/dedicated-game-servers
sources:
  - https://github.com/CraightonH/dedicated-game-servers

maintainers:
  - name: CraightonH
    url: https://github.com/CraightonH
